"""
PDF export service using ReportLab.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable


def generate_insights_pdf(
    insights_text: str,
    summary: dict[str, Any],
    filename: str = "dataset",
) -> bytes:
    """Generate a PDF report from AI insights and dataset summary."""
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Title"],
        fontSize=24,
        spaceAfter=6,
        textColor=colors.HexColor("#1e293b"),
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        spaceAfter=4,
        textColor=colors.HexColor("#2563eb"),
    )
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=11,
        leading=16,
        textColor=colors.HexColor("#374151"),
    )
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.HexColor("#6b7280"),
    )

    story: list[Any] = []

    # Title
    story.append(Paragraph("Data Analyst Copilot", title_style))
    story.append(Paragraph(f"AI Insights Report — {filename}", heading_style))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", meta_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e2e8f0")))
    story.append(Spacer(1, 0.15 * inch))

    # Dataset summary table
    shape = summary.get("shape", {})
    if shape:
        story.append(Paragraph("Dataset Overview", heading_style))
        data = [
            ["Metric", "Value"],
            ["Total Rows", str(shape.get("rows", "—"))],
            ["Total Columns", str(shape.get("columns", "—"))],
        ]
        num_summary = summary.get("numeric_summary", {})
        if num_summary:
            data.append(["Numeric Columns", str(len(num_summary))])
        cat_summary = summary.get("categorical_summary", {})
        if cat_summary:
            data.append(["Categorical Columns", str(len(cat_summary))])

        tbl = Table(data, colWidths=[2.5 * inch, 3 * inch])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8fafc"), colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(tbl)
        story.append(Spacer(1, 0.2 * inch))

    # AI Insights section
    story.append(Paragraph("AI-Generated Insights", heading_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0")))
    story.append(Spacer(1, 0.1 * inch))

    # Parse and render insights text (handle markdown-like bold)
    for line in insights_text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.08 * inch))
            continue
        # Convert **text** to <b>text</b> for ReportLab
        line = _md_to_rl(line)
        story.append(Paragraph(line, body_style))

    story.append(Spacer(1, 0.3 * inch))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#e2e8f0")))
    story.append(Spacer(1, 0.05 * inch))
    story.append(Paragraph("Generated by Data Analyst Copilot — AI-powered data analysis platform", meta_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()


def _md_to_rl(text: str) -> str:
    """Convert basic markdown (**, #) to ReportLab XML tags."""
    import re
    # Bold: **text**
    text = re.sub(r"\*\*(.+?)\*\*", r"<b>\1</b>", text)
    # Heading lines starting with #
    text = re.sub(r"^#{1,3}\s+", "", text)
    # Escape & that aren't part of XML entities
    text = re.sub(r"&(?!amp;|lt;|gt;|quot;|apos;)", "&amp;", text)
    return text
